ios/KaMPStarteriOS.xcodeproj/project.pbxproj, shared/build.gradle.kts
Remove team in iOS file, fixed test task after splitting ios gradle config
=> Fixed config

workflows.yml
Only building from gradle and running tests for the moment.
=> Add github actions build

build.gradle.kts, buildSrc/src/main/java/Dependencies.kt
=> Koin update

app/build.gradle.kts, buildSrc/src/main/java/Dependencies.kt
Seemed like we needed a refresh here
=> Dependency updates

ios/KaMPStarteriOS.xcodeproj/project.pbxproj, ios/KaMPStarteriOS/AppDelegate.swift, ios/KaMPStarteriOS/Base.lproj/Main.storyboard, ios/KaMPStarteriOS/BreedCell.swift, ios/KaMPStarteriOS/ViewController.swift
- optionals instead of force unwraps
- protocol delegation pattern replacing adapter in cells
- extensions for organization
=> Swift cleanup

app/src/main/java/co/touchlab/kampkit/android/MainApp.kt, ios/KaMPKitiOS.xcodeproj/project.pbxproj, ios/KaMPKitiOS/AppDelegate.swift, ios/KaMPKitiOS/Base.lproj/Main.storyboard, ios/KaMPKitiOS/Koin.swift, ios/KaMPKitiOS/ViewController.swift, shared/src/androidMain/kotlin/co/touchlab/kampkit/KoinAndroid.kt, shared/src/androidTest/kotlin/co/touchlab/kampkit/KoinTest.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/AppInfo.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/Koin.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/TestAppInfo.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/KoinIOS.kt, shared/src/iosTest/kotlin/co/touchlab/kampkit/KoinTest.kt
Had Koin on my mind tonight so I thought I'd give this a spin.
=> Initial PoC Koin refactor to try and tame API and configure from iOS side

app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/java/Dependencies.kt, gradle.properties, gradle/wrapper/gradle-wrapper.properties, shared/build.gradle.kts, shared/src/commonMain/kotlin/co/touchlab/kampkit/ktor/DogApiImpl.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedModel.kt
Also some reorganization inside Dependencies.kt
=> Update dependency versions

buildSrc/src/main/java/Dependencies.kt
[Summary]
Dependencies out of date:
- kotlin
- cocoapods ext
- coroutines
- ktor
- junit
- multiplatform settings
- stately
-serialization
[Fix]
Update dependencies in buildSrc/Dependencies.kt
[Testing]
Manually tested Android and iOS apps for correct behavior.
https://github.com/touchlab/KaMPKit/issues/154
=> Issue 154: Update dependencies

docs/GENERAL_ARCHITECTURE.md
For #167 
[Summary]
General architecture docs are out of date.
[Fix]
Remove references to Ktor hack we're no longer using, and the Koin fork
we're no longer using.
[Testing]
Pure documentation. None needed.
=> Issue 167: Please update the docs, they create confusion..

.github/pull_request_template.md, azure/android-pipeline.yml, azure/ios-pipeline.yml
Issue: https://github.com/touchlab/KaMPKit/issues/151
Aiming for more inclusive language, and following new policy from GitHub and others.
1. Change the default branch in Github (Done)
2. Update the default branch for Azure CI (this change)
- No testing yet. Will need to see if this triggers a build on a PR, but may not until it is merged into main.
=> [Issue-151] Rename "master" branch to "main"

.github/workflows/KaMPKit-Android.yml, .github/workflows/KaMPKit-Shared.yml, .github/workflows/KaMPKit-iOS.yml, README.md
[No issue]
Various inefficiencies in CI
1. Created a separate workflow for shared code
2. Ignore irrelevant file changes for the appropriate builds
3. Add ability to trigger manual builds
- To be seen
=> Workflow updates

app/build.gradle.kts, app/src/main/java/co/touchlab/kampkit/android/BreedViewModel.kt, app/src/main/java/co/touchlab/kampkit/android/MainActivity.kt, build.gradle.kts, buildSrc/src/main/java/Dependencies.kt, shared/build.gradle.kts, shared/shared.podspec, shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedModel.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/NativeViewModel.kt
Closes #194
We were still reading Koin from Bintray (oops!)
Update to release version of Koin which is published to Maven Central, and remove remaining stray Bintray dependencies
Unit tests still pass, and ran App on both platforms with no issues.
=> Issue-194: Remove Bintray dependencies and update to latest Koin release

app/src/main/java/co/touchlab/kampkit/android/BreedViewModel.kt, app/src/main/java/co/touchlab/kampkit/android/MainActivity.kt, app/src/main/java/co/touchlab/kampkit/android/ui/Composables.kt, gradle/libs.versions.toml, ios/KaMPKitiOS/AppDelegate.swift, ios/KaMPKitiOS/BreedListScreen.swift, shared/build.gradle.kts, shared/src/androidMain/kotlin/co/touchlab/kampkit/KoinAndroid.kt, shared/src/androidTest/kotlin/co/touchlab/kampkit/KoinTest.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/DatabaseHelper.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/Koin.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/ktor/DogApiImpl.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedModel.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/BreedModelTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/SqlDelightTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/TestUtil.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/KoinIOS.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/MainScope.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/NativeViewModel.kt, shared/src/iosTest/kotlin/co/touchlab/kampkit/KoinTest.kt
Bumps Kermit to 1.0.0
Pretty debug logging in xcode:
=> Kermit 1.0.0

app/build.gradle.kts, app/src/main/java/co/touchlab/kampkit/android/ui/Composables.kt, gradle.properties, gradle/libs.versions.toml, ios/Podfile.lock, ios/Pods/Local Podspecs/shared.podspec.json, ios/Pods/Manifest.lock, ios/Pods/Pods.xcodeproj/project.pbxproj, shared/build.gradle.kts, shared/shared.podspec, shared/src/androidTest/kotlin/co/touchlab/kampkit/BaseTest.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/ktor/DogApiImpl.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/BreedModelTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/mock/KtorApiMock.kt
This is using Compose 1.1.0-rc01 and ktor 2.0.0-beta-1. I'm opening it as a draft for now so we can wait on those to go stable.
=> New memory model

ios/Podfile.lock, ios/Pods/Local Podspecs/shared.podspec.json, ios/Pods/Manifest.lock, shared/build.gradle.kts, shared/shared.podspec
Removed the extra version assignment, and bumped the single version number.  Closes #234
=> Remove extra version assignment

gradle.properties, gradle/libs.versions.toml, ios/Podfile.lock, ios/Pods/Local Podspecs/shared.podspec.json, ios/Pods/Manifest.lock, ios/Pods/Pods.xcodeproj/project.pbxproj, shared/build.gradle.kts, shared/shared.podspec, shared/src/commonMain/kotlin/co/touchlab/kampkit/ktor/DogApiImpl.kt
=> Kotlin 1.6.20 and library version bumps

docs/GENERAL_ARCHITECTURE.md
[Issue: https://github.com/touchlab/KaMPKit/issues/[issue number]
](https://github.com/touchlab/KaMPKit/issues/256)
Docs update
Update GENERAL_ARCHITECTURE.md to better align with current implementation.
=> [ISSUE-256] Update GENERAL_ARCHITECTURE.md to better align with implementation

docs/TROUBLESHOOTING.md
Troubleshooting section on binary size
=> Binary size

docs/APP_BUILD.md, docs/TROUBLESHOOTING.md
Adds a section to the app build doc which describes our github actions config
=> Add section on CI Hosts

gradle/libs.versions.toml
Issue: https://github.com/touchlab/KaMPKit/issues/308
This got fixed with Latest `Ktor` version along with latest `coroutine` version
https://youtrack.jetbrains.com/issue/KTOR-5728
=> 308 - Fix an issue where iOS release build fails

.editorconfig, .idea/codeStyles/Project.xml, app/build.gradle.kts, app/src/main/kotlin/co/touchlab/kampkit/android/MainActivity.kt, app/src/main/kotlin/co/touchlab/kampkit/android/MainApp.kt, app/src/main/kotlin/co/touchlab/kampkit/android/ui/Composables.kt, app/src/main/kotlin/co/touchlab/kampkit/android/ui/theme/Shapes.kt, app/src/main/kotlin/co/touchlab/kampkit/android/ui/theme/Theme.kt, app/src/main/kotlin/co/touchlab/kampkit/android/ui/theme/Typography.kt, build.gradle.kts, shared/build.gradle.kts, shared/src/androidMain/kotlin/co/touchlab/kampkit/KoinAndroid.kt, shared/src/androidUnitTest/kotlin/co/touchlab/kampkit/KoinTest.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/DatabaseHelper.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/Koin.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedRepository.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedViewModel.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/response/BreedResult.kt, shared/src/commonMain/kotlin/co/touchlab/kampkit/sqldelight/CoroutinesExtensions.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/BreedRepositoryTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/BreedViewModelTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/DogApiTest.kt, shared/src/commonTest/kotlin/co/touchlab/kampkit/SqlDelightTest.kt, shared/src/iosMain/kotlin/co/touchlab/kampkit/KoinIOS.kt, shared/src/iosTest/kotlin/co/touchlab/kampkit/KoinTest.kt, shared/src/iosTest/kotlin/co/touchlab/kampkit/TestUtilIOS.kt
=> Updating KtLint
